### ISSUE TITLE
Working with Envoy Firmware v8?

### ISSUE THREAD

**Issue by timmyJB** [khandelwalpiyush/chargehq-enphase#1]
Hi there, thanks for creating this. I am trying to get it working without success.
My Envoy firmware is D8.2.114

Does this work with version 8?

Thanks so much.
Tim

**Comment by piyush-khandelwal-sp** [comment]
Hi @timmyJB 

Sorry haven't tested it as I am currently on D7.6.175 . Still working fine on that.

Thanks

**Comment by khandelwalpiyush** [comment]
Hi @timmyJB 

Sorry haven't tested it as I am currently on D7.6.175 . Still working fine on that.

Thanks

**Comment by timmyJB** [comment]
Ok!

I had trouble getting it running using TaskScheduler on Windows but got it working using Cygwin. This is with Envoy firmware D8. Looks to be working well. 

Thanks so much for creating. 
Awesome

**Comment by khandelwalpiyush** [comment]
Thanks @timmyJB good to know its working with D8 :) Closing it off and will update the readme file to say the same
